use crate::pb::lmtd_message::Payload as LmtdMessagePayload;

#[repr(u8)]
#[derive(Debug, Copy, Clone, Eq, Hash, PartialEq)]
pub enum LmtdMessagePayloadType {
    Addresses = 0,
    Block,
    Transaction,
    BlockLocator,
    RequestAddresses,
    RequestRelayBlocks,
    RequestTransactions,
    IbdBlock,
    InvRelayBlock,
    InvTransactions,
    Ping,
    Pong,
    Verack,
    Version,
    TransactionNotFound,
    Reject,
    PruningPointUtxoSetChunk,
    RequestIbdBlocks,
    UnexpectedPruningPoint,
    IbdBlockLocator,
    IbdBlockLocatorHighestHash,
    RequestNextPruningPointUtxoSetChunk,
    DonePruningPointUtxoSetChunks,
    IbdBlockLocatorHighestHashNotFound,
    BlockWithTrustedData,
    DoneBlocksWithTrustedData,
    RequestPruningPointAndItsAnticone,
    BlockHeaders,
    RequestNextHeaders,
    DoneHeaders,
    RequestPruningPointUtxoSet,
    RequestHeaders,
    RequestBlockLocator,
    PruningPoints,
    RequestPruningPointProof,
    PruningPointProof,
    Ready,
    BlockWithTrustedDataV4,
    TrustedData,
    RequestIbdChainBlockLocator,
    IbdChainBlockLocator,
    RequestAntipast,
    RequestNextPruningPointAndItsAnticoneBlocks,
}

impl From<&LmtdMessagePayload> for LmtdMessagePayloadType {
    fn from(payload: &LmtdMessagePayload) -> Self {
        match payload {
            LmtdMessagePayload::Addresses(_) => LmtdMessagePayloadType::Addresses,
            LmtdMessagePayload::Block(_) => LmtdMessagePayloadType::Block,
            LmtdMessagePayload::Transaction(_) => LmtdMessagePayloadType::Transaction,
            LmtdMessagePayload::BlockLocator(_) => LmtdMessagePayloadType::BlockLocator,
            LmtdMessagePayload::RequestAddresses(_) => LmtdMessagePayloadType::RequestAddresses,
            LmtdMessagePayload::RequestRelayBlocks(_) => LmtdMessagePayloadType::RequestRelayBlocks,
            LmtdMessagePayload::RequestTransactions(_) => LmtdMessagePayloadType::RequestTransactions,
            LmtdMessagePayload::IbdBlock(_) => LmtdMessagePayloadType::IbdBlock,
            LmtdMessagePayload::InvRelayBlock(_) => LmtdMessagePayloadType::InvRelayBlock,
            LmtdMessagePayload::InvTransactions(_) => LmtdMessagePayloadType::InvTransactions,
            LmtdMessagePayload::Ping(_) => LmtdMessagePayloadType::Ping,
            LmtdMessagePayload::Pong(_) => LmtdMessagePayloadType::Pong,
            LmtdMessagePayload::Verack(_) => LmtdMessagePayloadType::Verack,
            LmtdMessagePayload::Version(_) => LmtdMessagePayloadType::Version,
            LmtdMessagePayload::TransactionNotFound(_) => LmtdMessagePayloadType::TransactionNotFound,
            LmtdMessagePayload::Reject(_) => LmtdMessagePayloadType::Reject,
            LmtdMessagePayload::PruningPointUtxoSetChunk(_) => LmtdMessagePayloadType::PruningPointUtxoSetChunk,
            LmtdMessagePayload::RequestIbdBlocks(_) => LmtdMessagePayloadType::RequestIbdBlocks,
            LmtdMessagePayload::UnexpectedPruningPoint(_) => LmtdMessagePayloadType::UnexpectedPruningPoint,
            LmtdMessagePayload::IbdBlockLocator(_) => LmtdMessagePayloadType::IbdBlockLocator,
            LmtdMessagePayload::IbdBlockLocatorHighestHash(_) => LmtdMessagePayloadType::IbdBlockLocatorHighestHash,
            LmtdMessagePayload::RequestNextPruningPointUtxoSetChunk(_) => LmtdMessagePayloadType::RequestNextPruningPointUtxoSetChunk,
            LmtdMessagePayload::DonePruningPointUtxoSetChunks(_) => LmtdMessagePayloadType::DonePruningPointUtxoSetChunks,
            LmtdMessagePayload::IbdBlockLocatorHighestHashNotFound(_) => LmtdMessagePayloadType::IbdBlockLocatorHighestHashNotFound,
            LmtdMessagePayload::BlockWithTrustedData(_) => LmtdMessagePayloadType::BlockWithTrustedData,
            LmtdMessagePayload::DoneBlocksWithTrustedData(_) => LmtdMessagePayloadType::DoneBlocksWithTrustedData,
            LmtdMessagePayload::RequestPruningPointAndItsAnticone(_) => LmtdMessagePayloadType::RequestPruningPointAndItsAnticone,
            LmtdMessagePayload::BlockHeaders(_) => LmtdMessagePayloadType::BlockHeaders,
            LmtdMessagePayload::RequestNextHeaders(_) => LmtdMessagePayloadType::RequestNextHeaders,
            LmtdMessagePayload::DoneHeaders(_) => LmtdMessagePayloadType::DoneHeaders,
            LmtdMessagePayload::RequestPruningPointUtxoSet(_) => LmtdMessagePayloadType::RequestPruningPointUtxoSet,
            LmtdMessagePayload::RequestHeaders(_) => LmtdMessagePayloadType::RequestHeaders,
            LmtdMessagePayload::RequestBlockLocator(_) => LmtdMessagePayloadType::RequestBlockLocator,
            LmtdMessagePayload::PruningPoints(_) => LmtdMessagePayloadType::PruningPoints,
            LmtdMessagePayload::RequestPruningPointProof(_) => LmtdMessagePayloadType::RequestPruningPointProof,
            LmtdMessagePayload::PruningPointProof(_) => LmtdMessagePayloadType::PruningPointProof,
            LmtdMessagePayload::Ready(_) => LmtdMessagePayloadType::Ready,
            LmtdMessagePayload::BlockWithTrustedDataV4(_) => LmtdMessagePayloadType::BlockWithTrustedDataV4,
            LmtdMessagePayload::TrustedData(_) => LmtdMessagePayloadType::TrustedData,
            LmtdMessagePayload::RequestIbdChainBlockLocator(_) => LmtdMessagePayloadType::RequestIbdChainBlockLocator,
            LmtdMessagePayload::IbdChainBlockLocator(_) => LmtdMessagePayloadType::IbdChainBlockLocator,
            LmtdMessagePayload::RequestAntipast(_) => LmtdMessagePayloadType::RequestAntipast,
            LmtdMessagePayload::RequestNextPruningPointAndItsAnticoneBlocks(_) => {
                LmtdMessagePayloadType::RequestNextPruningPointAndItsAnticoneBlocks
            }
        }
    }
}
