#!/bin/bash
set -e

./build-web $@

if [ "$1" == "--keygen" ]; then
    echo "building keygen"
    typedoc --name "LMT WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/lmt-keygen ./build/docs/lmt-keygen.ts
elif [ "$1" == "--rpc" ]; then
    echo "building rpc"
    typedoc --name "LMT WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/lmt-rpc ./build/docs/lmt-rpc.ts
elif [ "$1" == "--core" ]; then
    echo "building core"
    typedoc --name "LMT WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/lmt-core ./build/docs/lmt-core.ts
elif [ "$1" == "--sdk" ]; then
    echo "building full"
    typedoc --name "LMT WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/lmt ./build/docs/lmt.ts
else
    echo "building keygen"
    typedoc --name "LMT WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/lmt-keygen ./build/docs/lmt-keygen.ts
    echo "building rpc"
    typedoc --name "LMT WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/lmt-rpc ./build/docs/lmt-rpc.ts
    echo "building core"
    typedoc --name "LMT WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/lmt-core ./build/docs/lmt-core.ts
    echo "building full"
    typedoc --name "LMT WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/lmt ./build/docs/lmt.ts

fi