#!/bin/bash
# This script builds the Rusty LMT WASM32 SDK release.

# make the script fail for any failed command
set -e

# Workaround for Rust 1.87.0
# https://github.com/rust-lang/rust/issues/141048
export RUSTFLAGS=-Ctarget-cpu=mvp

rm -rf release/*
rm -rf web/*
rm -rf nodejs/*
rm -rf docs/*
rm -rf examples/nodejs/typescript/lib

mkdir -p release/lmt-wasm32-sdk/web
mkdir -p release/lmt-wasm32-sdk/nodejs
mkdir -p release/lmt-wasm32-sdk/docs

# pushd .
# cd ../rpc/wrpc/wasm
# wasm-pack build --target web --out-name lmt-rpc --out-dir web/lmt-rpc --features wasm32-sdk $@
# popd

wasm-pack build --weak-refs --target web --out-name lmt --out-dir web/lmt-keygen --features wasm32-keygen $@
wasm-pack build --weak-refs --dev --target web --out-name lmt --out-dir web/lmt-keygen-dev --features wasm32-keygen $@

wasm-pack build --weak-refs --target web --out-name lmt --out-dir web/lmt-rpc --features wasm32-rpc $@
wasm-pack build --weak-refs --dev --target web --out-name lmt --out-dir web/lmt-rpc-dev --features wasm32-rpc $@

wasm-pack build --weak-refs --target web --out-name lmt --out-dir web/lmt-core --features wasm32-core $@
wasm-pack build --weak-refs --dev --target web --out-name lmt --out-dir web/lmt-core-dev --features wasm32-core $@

wasm-pack build --weak-refs --target web --out-name lmt --out-dir web/lmt --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target web --out-name lmt --out-dir web/lmt-dev --features wasm32-sdk $@

wasm-pack build --weak-refs --target nodejs --out-name lmt --out-dir nodejs/lmt --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target nodejs --out-name lmt --out-dir nodejs/lmt-dev --features wasm32-sdk $@

# wasm-pack build --target web --dev --out-name lmt --out-dir build/docs/lmt --features wasm32-sdk $@
typedoc --name "LMT WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/lmt-keygen ./build/docs/lmt-keygen.ts
typedoc --name "LMT WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/lmt-rpc ./build/docs/lmt-rpc.ts
typedoc --name "LMT WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/lmt-core ./build/docs/lmt-core.ts
typedoc --name "LMT WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/lmt ./build/docs/lmt.ts

# cp -r ../rpc/wrpc/wasm/web/lmt-rpc release/lmt-wasm32-sdk/web/lmt-rpc
cp -r web/lmt-keygen release/lmt-wasm32-sdk/web/lmt-keygen
cp -r web/lmt-keygen-dev release/lmt-wasm32-sdk/web/lmt-keygen-dev

cp -r web/lmt-rpc release/lmt-wasm32-sdk/web/lmt-rpc
cp -r web/lmt-rpc-dev release/lmt-wasm32-sdk/web/lmt-rpc-dev

cp -r web/lmt-core release/lmt-wasm32-sdk/web/lmt-core
cp -r web/lmt-core-dev release/lmt-wasm32-sdk/web/lmt-core-dev

cp -r web/lmt release/lmt-wasm32-sdk/web/lmt
cp -r web/lmt-dev release/lmt-wasm32-sdk/web/lmt-dev

cp -r nodejs/lmt release/lmt-wasm32-sdk/nodejs/lmt
cp -r nodejs/lmt-dev release/lmt-wasm32-sdk/nodejs/lmt-dev

cp -r docs/lmt-keygen release/lmt-wasm32-sdk/docs/lmt-keygen
cp -r docs/lmt-rpc release/lmt-wasm32-sdk/docs/lmt-rpc
cp -r docs/lmt-core release/lmt-wasm32-sdk/docs/lmt-core
cp -r docs/lmt release/lmt-wasm32-sdk/docs/lmt

mkdir -p release/lmt-wasm32-sdk/examples/data
if [ -f examples/data/.gitignore ]; then
  cp -r examples/data/.gitignore release/lmt-wasm32-sdk/examples/data/.gitignore
else
  # Keep the folder in packaged artifacts even if source .gitignore is absent.
  touch release/lmt-wasm32-sdk/examples/data/.gitignore
fi
cp -r examples/nodejs release/lmt-wasm32-sdk/examples/
cp -r examples/web release/lmt-wasm32-sdk/examples/
cp -r examples/init.js release/lmt-wasm32-sdk/examples/
cp -r examples/jsconfig.json release/lmt-wasm32-sdk/examples/
cp -r examples/package.json release/lmt-wasm32-sdk/examples/

pushd .
cd release/lmt-wasm32-sdk/examples
npm install
popd

# tsc release/lmt-wasm32-sdk/examples/nodejs/typescript/

cp index.html release/lmt-wasm32-sdk/index.html
cp README.md release/lmt-wasm32-sdk/README.md
cp CHANGELOG.md release/lmt-wasm32-sdk/CHANGELOG.md
cp LICENSE release/lmt-wasm32-sdk/LICENSE

node build/package-sizes.js
cp package-sizes.js release/lmt-wasm32-sdk/package-sizes.js

pushd .
cd release
zip -q -r lmt-wasm32-sdk.zip lmt-wasm32-sdk
popd
